Keep Mod Entity List
--------------------
[cols="1 v,1 v,1 v,1 v,50 l",width="25%"]
|===
5+s|trigger_victory
5+|Point
5+|Drake
5+|Automatically fires its targets when the last enemy has been killed in a map.  Does not require targetname.
|target `REQUIRED`|string 3+|The name of the object(s) to have run the `use` function on.
5+|same for target2, target3, target4, statetarget1, statetarget2,...statetarget24
|killtarget|string 3+|The name of the object(s) to delete from the world.
5+|same for killtarget2.
|===

{blank} + 

[cols="1 v,1 v,1 v,1 v,1 l",width="50%"]
|===
5+s|trigger_monsterpassivestate
5+|Point
5+|Arcane Dimensions
5+|Toggle passive state on targetted monster(s).
|targetname `REQUIRED`|string 3+|The name of this entity for use by an activator.
|target `REQUIRED`|trilean 3+|The name of the object(s) to change the 
`passive_state` on.  Must be alive, a monster, not be marked
with spawnflag to spawn angry, not have `passive_state` of -1
(NEVER), not be insane `temperament`, not be marked with 
`ryuflags` 4096 for forced to shoot, and not have `alignment`
of 1 (Good).  Will run targets on `passive_eventon` or
`passive_eventoff` if set on any monsters that this affects;
this is used to run these targets when passive is activated or
deactivated for that individual monster.  Useful to use
the monster as its own trigger_relay to reset stuff on change.
|state|int|[-1,0,1,2]|0|The value to set `passive_state` on targeted enemy.
All of the following have the potential to put target
into Reset state if they already have an enemy and
were passive previously; this will cause the monster
to transition to passive once they are done fighting
but otherwise has no affect if they weren't passive.
-1 = No change to state.
0 = Set to Angry, normal reaction on sight.
1 = Set to Passive, won't attack unless provoked.
2 = Toggle to opposite of current state.
|wait|int|[-8388608,8388608]|0|Ignored unless -1 for activate only once.
|===

{blank} + 

[cols="1 v,1 v,1 v,1 v,1 l",width="50%"]
|===
5+s|path_corner
5+|Point
5+|ID1
5+|Waypoint for entities to use for following.  Typically used for func_train and
monsters.  Capable of stopping indefinitely, restarting after stopping at the
corner, waiting at the corner a specific amount of time, splitting the path to
an alternative corner, and triggering targets when this corner is reached.
|targetname `REQUIRED`|string 3+|Name of current path corner
|corner_event|string 3+|Name of target(s) to trigger when used or touched.
|corner_route|int|[0,1,2,3,4,5]|0|Change path_corner route.
1 = Forward
2 = Alternative forward
3 = Backward
4 = Exact using `state`
5 = Random
|corner_switch|int|[-1,0,1,2]|0|Change spawnflags REVERSE.
-1 = No
0 = Do nothing
1 = Yes
2 = Toggle
|corner_pause|int|[-1,0,1,2]|0|Change spawnflags NOPAUSE.
-1 = No
0 = Do nothing
1 = Yes
2 = Toggle
|corner_pstate|int|[-1,0,1,2]|0|Change passive state, on monsters only.
-1 = Off
0 = Do nothing
1 = On
2 = Toggle
|state|int|[1,2,3,4,5]|1|Starting route. This changes when passed based on `spawnflags`.
1 = Forward, uses `target`
2 = Alternative forward, uses `target2`
3 = Backward, uses `targetback`
|target|string 3+|Targetname of FORWARD route
|target2|string 3+|Alternative FORWARD route
|targetback|string 3+|Override default BACKWARD route
|delay|float|[-8388608,8388608]|0.00|Random amount of time to pause here.
|alpha|float|[0,1.00]|0.35|Override for visual arrows with developer > 0.
|speed|float|[0,8388608]|0|Change speed of func_train here.  0 does nothing.
5+|spawnflags:
1 EXACT : Exact route logic (unchecked=random route choices).
2 INSTANT : Move instantly to this corner if next destination.
4 REVERSE : Train direction is reversed for next corner.
8 NOPAUSE : Train does not pause on this path corner.
5+|Compatability support but not intended for normal usage
|corner_speed|float|[0,8388608]|0|Duplicate of `speed`.
|===

{blank} + 

[cols="1 v,1 v,1 l,1 v,1 l",width="50%"]
|===
5+s|func_breakable
5+|Solid
5+|Arcane Dimensions
5+|Spawn breakable objects from a bmodel
|target|string 3+|targets to fire when breakable is dead/used (only used once)
|target2|string 3+|Additional trigger function (need target to be defined as well)
|style|int|[1,2,3,4,5,6,10]|1|Pre-defined sound/model types
1 = Rock
2 = Wood
3 = Glass
4 = Metal
5 = Brick
6 = Ceramic
10 = Custom
|brksound|int|[1,2,3,4,5,6,10]|1|Initial breaking sound type (override style default)
1 = Rock
2 = Wood
3 = Glass
4 = Metal
5 = Brick
6 = Ceramic
10 = Custom
|brkimpsound|int|[1,2,3,4,5,6,10]|1|Impact sound type (override style default)
1 = Rock
2 = Wood
3 = Glass
4 = Metal
5 = Brick
6 = Ceramic
10 = Custom
|brkobjects|int|[1,5,10,11,12,13,14,15,20,21,
22,30,31,32,33,40,41,42,
43,44,50,51,52,53,54,55,
56,60]|1|Breakable object model type.
1 = Self, Single self models
5 = Custom, Custom models
10 = Rock 1, ID rock4_1 (dark large bricks)
11 = Rock 2, ID rock4_2 (light stone)
12 = Rock 3, ID rock3_8 (light vertical)
13 = Rock 4, ID city5_3 (white plaster)
14 = Rock 5, ID stone1_7b (dark blue ver)
15 = Rock 6, ID cliff4 (black rock)
20 = Wood 1, ID dung01_3 (dark)
21 = Wood 2, ID dung01_2 (light)
22 = Wood 3, ID wizwood1_7 (mouldy)
30 = Glass 1, ID window1_2 (blue sqr)
31 = Glass 2, ID window01_4 (red stain)
32 = Glass 3, ID window02_1 (yellow stain)
33 = Glass 4, ID window01_3 (purple stain)
40 = Metal 1, ID metal1_2 (brown generic)
41 = Metal 2, ID metal4_5 (metal4_4 generic)
42 = Metal 3, ID metal4_7 (rivet metal panels)
43 = Metal 4, ID cop1_1 (green generic)
44 = Metal 5, ID metal2_8 (blue generic)
50 = Brick 1, ID wbrick1_5 (large brown)
51 = Brick 2, ID city2_3 (small sewer green)
52 = Brick 3, ID city6_8 (small drywall greyish)
53 = Brick 4, ID wiz1_4 (large white)
54 = Brick 5, ID city2_1 (small red brick)
55 = Brick 6, ID city1_6 (small brown brick)
56 = Brick 7, ID city4_5 (small blue brick)
60 = Ceramic 1, Ceramic pot
|noise|string 3+|Initial breaking sound (unique sound file)
|noise1|string 2+|"quoth/impact/rock1.wav"|Custom Rubble Impact sounds
|noise2|string 3+|Custom Rubble Impact sound 2
|noise3|string 3+|Custom Rubble Impact sound 3
|noise4|string 3+|Custom Rubble Impact sound 4
|brkobj1|string 2+|`brkobjects` = 10: "maps/ad_brk/rock01.bsp"
`brkobjects` = 11 (Rock 1): "maps/ad_brk/rock05.bsp"
`brkobjects` = 12 (Rock 2): "maps/ad_brk/rock09.bsp"
`brkobjects` = 13 (Rock 3): "maps/ad_brk/rock13.bsp"
`brkobjects` = 14 (Rock 4): "maps/ad_brk/rock17.bsp"
`brkobjects` = 15 (Rock 5): "maps/ad_brk/rock21.bsp"
`brkobjects` = 20 (Wood 1): "maps/ad_brk/wood01.bsp"
`brkobjects` = 21 (Wood 2): "maps/ad_brk/wood05.bsp"
`brkobjects` = 22 (Wood 3): "maps/ad_brk/wood09.bsp"
`brkobjects` = 30 (Glass 1): "maps/ad_brk/glass01.bsp"
`brkobjects` = 31 (Glass 2): "maps/ad_brk/glass05.bsp"
`brkobjects` = 32 (Glass 3): "maps/ad_brk/glass09.bsp"
`brkobjects` = 33 (Glass 4): "maps/ad_brk/glass013.bsp"
|Custom Rubble bmodel objects (unique models, must have 1 defined)
brkobj2|string 3+|Custom Rubble bmodel objects 2
brkobj3|string 3+|Custom Rubble bmodel objects 3
brkobj4|string 3+|Custom Rubble bmodel objects 4
health    : amount of damage to take before breaking (def 1)
count     : minimum quantity to spawn (def 4)
cnt       : random quantity to spawn (def 4) =-1 no random qty
dmg       : explosive radius damage (emits from center of func object)
pos1      : x=start particle colour, y=random range, z=quantity
brkvelbase : Base amount for velocity of broken parts (def "50 50 100")
brkveladd : Random additions for velocity of broken parts (def "100 100 150")
brkavel   : Amount of breaking object angle velocity (def 200)
brkfade   : Fade time before rubble fades away (def 4+random()x4)
brkmondmg : Damage multiplier for monster damage against breakable
angles    : direction to throw rubble (override default = impact direction)
brktrigjump    : Trigger if damaged by jumping monster attack
brktrigmissile : Trigger if damaged by rocket/grenade/shalball/radiusdmg
brktrignoplayer: No player/clients can damage this breakable
brkgravity     : Change the gravity for rubble, useful for underwater (Value = 0-1)
5+|spawnflags:
STARTOFF  : Will wait for trigger to spawn
NODAMAGE  : Cannot be damaged or shot, trigger only
EXPLOSION : trigger sprite/particle explosion
SILENT    : No initial breakage sound
DAMAGE    : Spawning rubble can damage (def = 2, use dmg key for touch damage)
NOMONSTER : monsters cannot damage this breakable and/or spawning rubble will not damage monsters
NOSOUND   : Spawning rubble has no impact sounds
NOROTATE  : Spawning rubble has No Y rotation
|===