#!/bin/bash
# Reads entities from the text file next to it named entities.txt and
# creates dendron notes for them as empty markdown stubs.  Assumes that
# entities list was generated by Nifty tool by Josiah Jack.
#
# This is also written by Josiah Jack, 4/19/2023.

while IFS= read -r entity; do
  if [[ "$entity" == monster_* ]]; then
    dendron_title="enemies.${entity}"
  elif [[ "$entity == item_* ]]; then
    dendron_title="items.${entity}"
  elif [[ "$entity == weapon_* ]]; then
    dendron_title="weapons.${entity}"
  elif [[ "$entity == trap_* ]]; then
    dendron_title="traps.${entity}"
  elif [[ "$entity == ltrail_* ]]; then
    dendron_title="traps.${entity}"
  elif [[ "$entity == trigger_* ]]; then
    dendron_title="brush-entities.triggers.${entity}"
  elif [[ "$entity == t_effector_* ]]; then
    dendron_title="brush-entities.triggers.${entity}"
  elif [[ "$entity == func_* ]]; then
    dendron_title="brush-entities.${entity}"
  elif [[ "$entity == fx_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == tele_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == env_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == misc_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == corpse_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == obj_* ]]; then
    dendron_title="point-entities.effects-and-decorations.${entity}"
  elif [[ "$entity == ambient_* ]]; then
    dendron_title="point-entities.ambients-and-sound-effects.${entity}"
  else
    dendron_title="point-entities.${entity}"
  fi

  npx dendron note write --fname "${dendron_title}"
done < ./entities.txt
